Description: CloudFormation template for creating an ec2 instance
Parameters:
  KeyName:
    Description: Key Pair name
    Type: 'AWS::EC2::KeyPair::KeyName'
    #Default: north-virginia
  VPC:
    Type: 'AWS::EC2::VPC::Id'
    Default: vpc-0a4e2777
  Subnet:
    Type: 'AWS::EC2::Subnet::Id'
    Default: subnet-06c89659
  InstanceType:
    Description: Select one of the possible instance types
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup::Id'
    Default: sg-08db17bdc52fb1a98
    AllowedValues:
      - sg-043316ca5a2bad564
      - sg-08db17bdc52fb1a98
      - sg-092b51f641c9f8509
Resources:
  Server:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0c2b8ca1dad447f8a
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      SecurityGroupIds:
        - Ref: SecurityGroup
      SubnetId:
        Ref: Subnet
Outputs:
  PublicName:
    Value:
      'Fn::GetAtt':
        - Server
        - PublicDnsName
    Description: Public name (connect via SSH)
